[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
base64 = "0.22.1"
clap = { version = "4.5.28", features = ["derive"] }
rand = "0.9.0"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
shared = { path = "../shared" }
