[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
base64 = "0.22.1"
rs_merkle = "1.4.2"
rusqlite = "0.33.0"
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.138"
shared = { path = "../shared" }
